export const courses = [
    {id:1,
        image: '../assets/images/course 1.jpg',
    title:'machine learning a-z: hands-on python',
    duration: '10',
    price: '200',
    rating: '4.1',
    category: 'Programming',
    instructor: 'Tylor wood',
    instructor_image: '../assets/images/tutor 1.png',
    },
    {id:2,image: '../assets/images/course 2.jpg',
    title:'Best law practices for absolute beginners',
    duration: '10',
    price: '200',
    rating: '4.3',
    category: 'Law',
    instructor: 'jessica hinch',
    instructor_image: '../assets/images/tutor 2.png',
    },
    {id:3,image: '../assets/images/course 3.jpg',
    title:'machine learning a-z: hands-on python',
    duration: '10',
    price: '200',
    rating: '4.1',
    category: 'Programming',
    instructor: 'Tylor wood',
    instructor_image: '../assets/images/tutor 3.png',
    },
     {id:4,image: '../assets/images/course 1.jpg',
    title:'machine learning a-z: hands-on python',
    duration: '10',
    price: '200',
    rating: '4.1',
    category: 'Programming',
    instructor: 'Tylor wood',
    instructor_image: '../assets/images/tutor 1.png',
    },
    {id:5,image: '../assets/images/course 2.jpg',
    title:'Best law practices for absolute beginners',
    duration: '10',
    price: '200',
    rating: '4.3',
    category: 'Law',
    instructor: 'jessica hinch',
    instructor_image: '../assets/images/tutor 2.png',
    },
    {id:6,image: '../assets/images/course 3.jpg',
    title:'machine learning a-z: hands-on python',
    duration: '10',
    price: '200',
    rating: '4.1',
    category: 'Programming',
    instructor: 'Tylor wood',
    instructor_image: '../assets/images/tutor 3.png',
    },
        {id:7,
        image: '../assets/images/course 1.jpg',
    title:'machine learning a-z: hands-on python',
    duration: '10',
    price: '200',
    rating: '4.1',
    category: 'Programming',
    instructor: 'Tylor wood',
    instructor_image: '../assets/images/tutor 1.png',
    },
    {id:8,image: '../assets/images/course 2.jpg',
    title:'Best law practices for absolute beginners',
    duration: '10',
    price: '200',
    rating: '4.3',
    category: 'Law',
    instructor: 'jessica hinch',
    instructor_image: '../assets/images/tutor 2.png',
    },
    {id:9,image: '../assets/images/course 3.jpg',
    title:'machine learning a-z: hands-on python',
    duration: '10',
    price: '200',
    rating: '4.1',
    category: 'Programming',
    instructor: 'Tylor wood',
    instructor_image: '../assets/images/tutor 3.png',
    },
     {id:10,image: '../assets/images/course 1.jpg',
    title:'machine learning a-z: hands-on python',
    duration: '10',
    price: '200',
    rating: '4.1',
    category: 'Programming',
    instructor: 'Tylor wood',
    instructor_image: '../assets/images/tutor 1.png',
    },
    {id:11,image: '../assets/images/course 2.jpg',
    title:'Best law practices for absolute beginners',
    duration: '10',
    price: '200',
    rating: '4.3',
    category: 'Law',
    instructor: 'jessica hinch',
    instructor_image: '../assets/images/tutor 2.png',
    },
    {id:12,image: '../assets/images/course 3.jpg',
    title:'machine learning a-z: hands-on python',
    duration: '10',
    price: '200',
    rating: '4.1',
    category: 'Programming',
    instructor: 'Tylor wood',
    instructor_image: '../assets/images/tutor 3.png',
    },
]