import { Course } from "src/app/classes/course";

export const test:Course[] = [
    {
    courseId: 1,
    courseName: 'Angular full course',
    courseDescription: '',
    coursePrice: 700,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'future',
    courseImage: null,
    },
    {
    courseId: 2,
    courseName: 'Java Multithreading',
    courseDescription: '',
    coursePrice: 340,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'future',
    courseImage: null,
    },
    {
    courseId: 3,
    courseName: 'React course',
    courseDescription: '',
    coursePrice: 49,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'future',
    courseImage: null,
    },
    {
    courseId: 3,
    courseName: '.net course',
    courseDescription: '',
    coursePrice: 29,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'future',
    courseImage: null,
    },
    {
    courseId: 3,
    courseName: 'abap course',
    courseDescription: '',
    coursePrice: 999,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'future',
    courseImage: null,
    },
    {
    courseId: 5,
    courseName: 'new full course',
    courseDescription: '',
    coursePrice: 34,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'past',
    courseImage: null,
    },
    {
    courseId: 2,
    courseName: 'Java only one',
    courseDescription: '',
    coursePrice: 34,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'present',
    courseImage: null,
    },
    {
    courseId: 3,
    courseName: 'nextjs course',
    courseDescription: '',
    coursePrice: 34,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'past',
    courseImage: null,
    },
    {
    courseId: 1,
    courseName: 'vuejs full course',
    courseDescription: '',
    coursePrice: 34,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'present',
    courseImage: null,
    },
    {
    courseId: 2,
    courseName: 'Java spring hibernate',
    courseDescription: '',
    coursePrice: 34,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'present',
    courseImage: null,
    },
    {
    courseId: 3,
    courseName: 'MERN course',
    courseDescription: '',
    coursePrice: 34,
    courseDuration: 2,
    courseDate: new Date(),
    courseTutorId: 12,
    courseRating: 2,
    courseStatus: 'past',
    courseImage: null,
    },
]